version: '3'
services:
  db:
    image: 'mongo:latest'
    container_name: mongodb
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - './docker-config/mongodb:/data/configdb'
    ports:
      - '27017:27017'
    networks:
      ai_net:
        ipv4_address: 172.16.238.5
  
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: dockerfile
    image: 'backend:latest'
    expose:
      - 8080
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      ai_net:
        ipv4_address: 172.16.238.10
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: dockerfile-prod
    image: 'frontend:latest'
    volumes:
      # Map ./frontend to ./app for development (remove and rebuild for production)
      # - ./frontend:/app
      # Use a persistent volume for node_modules so that it does not get mapped
      - node_modules:/app/node_modules
    expose:
      - 80
    ports:
      - '8000:80'
      # - '4200:4200'
    depends_on:
      - backend
    networks:
      ai_net:
        ipv4_address: 172.16.238.15

networks:
  ai_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
volumes:
  node_modules: