version: '3'
services:
  db:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./tmp/configdb:/data/configdb
    ports:
      - 27017:27017
  lab3:
    container_name: lab3
    build:
      context: .
      dockerfile: dockerfile
    image: lab3:latest
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db