version: '3'
services:
  db:
    image: 'mongo:latest'
    container_name: mongodb
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - './docker-config/mongodb:/data/configdb'
    ports:
      - '27017:27017'
  
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: dockerfile
    image: 'backend:latest'
    expose:
      - 8080
    ports:
      - '8080:8080'
    depends_on:
      - db
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    image: 'frontend:latest'
    expose:
      - 80
    ports:
      - '80:8000'
      - '4200:4200'
    depends_on:
      - backend
