version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    image: 'frontend:latest'
    volumes:
      # Map ./frontend to ./app for development (remove and rebuild for production)
      - ./frontend:/app
      # Use a persistent volume for node_modules so that it does not get mapped
      - node_modules:/app/node_modules
    expose:
      - 80
    ports:
      - '80:8000'
      - '4200:4200'
