pipeline {
    agent {
        'm2'
    }
    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                // git 'https://github.com/RedLicorice/progetto_ai_2018'
                sh 'mvn clean install'
            }
        }
        //stage('Test') {
        //    steps {
                // sh 'mvn test'
            // }
            // post {
                // always {
                    // junit 'target/surefire-reports/*.xml'
                // }
            // }
        // }

		post {
            // If Maven was able to run the tests, even if some of the test
            // failed, record the test results and archive the jar file.
            success {
               //junit '**/target/surefire-reports/TEST-*.xml'
               archiveArtifacts 'target/*.jar'
            }
         }
    }
}